<?php
//基础常量
define('SHARE_PATH','../shared');
define('ADMIN_THEME','default');//模版风格名称
define('TPL_NAME','tpl');//模版文件名称
define('N5_COMON_MODELS','../shared/models');//模版文件名称
//模版配置信息 
$Admin_theme=array('default'=>array('autor'=>'978873550@qq.com','doc_name'=>'default','version'=>'1.0'));
?>